default: &default
  adapter: postgresql
  encoding: unicode
  template: template0
  timeout: 5000

development:
  <<: *default
  url: postgresql://dev:dev@192.168.106.232/farkle_development?pool=5

test:
  <<: *default
  url: postgresql://dev:dev@192.168.106.232/farkle_test?pool=5

production:
  <<: *default
  url: postgres://gnwqdavsltefnn:df5b5b39e8cd4ce7ce33b52e70da052147a1cf3a10a26dbb7483dce3232c4233@ec2-52-54-174-5.compute-1.amazonaws.com:5432/d7cl112e4h62e1?pool=5
